shard = "tompkins"

{% for i in range(5000) %}
[[monsters]]
  deployment = "single"

  [monsters.monster]
    race = 'ogre'
    health = 1000

  [monsters.monster.location]
    type = "Point"
    #coordinates = {{ coordinates(42.8134055, -84.7837708, spread=0.0001) }}
    coordinates = {{ coordinates(42.8134055, -84.7837708, spread=1) }}

  [monsters.monster.name]
    first = "An Ogre"

  [monsters.monster.profession]
    title = "wizard"

  [monsters.monster.state]
    hostile = true

  [monsters.monster.level]
    current = 1
    experience = 500

  [monsters.monster.attributes]
    strength = 10
    dexterity = 10
    constitution = 10
    intelligence = 10
{% endfor %}
