shard = "tompkins"

{% for i in range(250) %}
[[monsters]]
  deployment = "single"

  [monsters.monster]
    race = 'ogre'
    profession = 'wizard'
    health = 1000

  [monsters.monster.location]
    type = "Point"
    coordinates = {{ coordinates(-84.54194682144171, 42.41184078897055, spread=0.001) }}
    #coordinates = {{ coordinates(-84.54194682144171, 42.41184078897055, spread=1) }}

  [monsters.monster.name]
    first = "An Ogre"

  [monsters.monster.state]
    hostile = true

  [monsters.monster.level]
    current = 1
    experience = 500

  [monsters.monster.attributes]
    strength = 10
    dexterity = 10
    constitution = 10
    intelligence = 10
{% endfor %}

{% for i in range(25) %}
[[monsters]]
  deployment = "single"

  [monsters.monster]
    race = 'ogre'
    profession = 'wizard'
    health = 1000

  [monsters.monster.location]
    type = "Point"
    coordinates = {{ coordinates(-84.54324232839487, 42.41172593043345, spread=0.001) }}
    #coordinates = {{ coordinates(-84.54324232839487, 42.41172593043345, spread=0.1) }}

  [monsters.monster.name]
    first = "An Ogre Brute"

  [monsters.monster.state]
    hostile = true

  [monsters.monster.level]
    current = 1
    experience = 500

  [monsters.monster.attributes]
    strength = 10
    dexterity = 10
    constitution = 10
    intelligence = 10
{% endfor %}

[[monsters]]
  deployment = "single"

  [monsters.monster]
    race = 'ogre'
    profession = 'wizard'
    health = 1000

  [monsters.monster.location]
    type = "Point"
    coordinates = {{ coordinates(-84.5441585559851, 42.411717568060226, spread=0) }}

  [monsters.monster.name]
    first = "Ogre Lord"

  [monsters.monster.state]
    hostile = true

  [monsters.monster.level]
    current = 1
    experience = 500

  [monsters.monster.attributes]
    strength = 10
    dexterity = 10
    constitution = 10
    intelligence = 10
